# Generated by Django 4.0.6 on 2022-07-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0002_blog_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='writer',
        ),
    ]
