# Generated by Django 4.0.6 on 2022-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0004_blog_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feelings',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='writer',
            field=models.CharField(blank=True, default='세은', max_length=20, null=True),
        ),
    ]
